# Generated by Django 4.1.7 on 2023-06-07 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0004_user_age_alter_groupchat_id_alter_usergrchat_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
