# Generated by Django 4.1.7 on 2023-08-23 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('demo', '0006_user_age'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.IntegerField(max_length=3, null=True),
        ),
    ]
